# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_difficulty_params <- function(difficulty) {
    .Call(`_TakuzuKL_get_difficulty_params`, difficulty)
}

generate_takuzu <- function(n, fill_percentage, chaotic = TRUE) {
    .Call(`_TakuzuKL_generate_takuzu`, n, fill_percentage, chaotic)
}

